<?php

return [
    "autor/author" =>                                        "item.authority_roles.author",
    "autor predlohy/after" =>                                "item.authority_roles.after",
    "ateliér/atelier" =>                                     "item.authority_roles.atelier",
    "okruh autora/circle of" =>                              "item.authority_roles.circle",
    "kopista/copyist of" =>                                  "item.authority_roles.copyist",
    "autor návrhu/draft by" =>                               "item.authority_roles.draft",
    "kresliar/draftsman" =>                                  "item.authority_roles.drawer",
    "rytec/engraver" =>                                      "item.authority_roles.engraver",
    "napodobňovateľ/epigone of" =>                           "item.authority_roles.epigone",
    "nasledovník/follower of" =>                             "item.authority_roles.follower",
    "pôvodné určenie/formerly attributed to" =>              "item.authority_roles.former",
    "grafik/graphic artist" =>                               "item.authority_roles.graphic",
    "autor úpravy záznamu/modified by" =>                    "item.authority_roles.modifier",
    "štúdio/office of" =>                                    "item.authority_roles.office",
    "autor origináu/original by" =>                          "item.authority_roles.original",
    "tlačiar/printer" =>                                     "item.authority_roles.printer",
    "pravdepodobne/probably by" =>                           "item.authority_roles.probably",
    "pravdepodobný autor predlohy/probably after" =>         "item.authority_roles.probablyAfter",
    "pravdepodobne okruh autora/probably circle of" =>       "item.authority_roles.probablyCircle",
    "pravdepodobne kresliar/probable draftsman" =>           "item.authority_roles.probablyDrawer",
    "pravdepodobne rytec/probable engraver" =>               "item.authority_roles.probablyEngraver",
    "pravdepodobne tlačiar/probable printer" =>              "item.authority_roles.probablyPrinter",
    "pravdepodobne dielňa autora/probably workshop of" =>    "item.authority_roles.probablyWorkshop",
    "výrobca/producer" =>                                    "item.authority_roles.producer",
    "vydavateľ/publisher" =>                                 "item.authority_roles.publisher",
    "reštaurátor/restorer" =>                                "item.authority_roles.restorer",
    "dielňa autora/workshop of" =>                           "item.authority_roles.workshop",
    "autor konceptu/concept by" =>                           "item.authority_roles.concept",
    "autor fotografie/photographer" =>                       "item.authority_roles.photograph",
];
