on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: [self-hosted, macOS, X64]

    steps:
      - uses: actions/checkout@v4

      - name: Add PHP, Composer and npm to PATH
        run: echo "/opt/homebrew/opt/php@8.1/bin:/usr/local/bin:/opt/homebrew/bin" >> $GITHUB_PATH

      - name: Check PHP version
        run: php -v

      - name: Check Composer version
        run: composer --version

      - name: Check npm version
        run: npm -v

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-

      - name: Install npm dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Run migrations
        run: php artisan migrate --env=testing

      # Seedovanie vynechané

      - name: Run tests
        run: php artisan test
        env:
          APP_KEY: SomeRandomStringSomeRandomString
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: root
          DB_DATABASE: webumenia_test
          DB_PASSWORD: ""
          ELASTICSEARCH_HOST: 127.0.0.1
          ELASTICSEARCH_PORT: 9200

