on:
  push:
    tags:
      - '2.106.2'

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, macOS, X64]

    steps:
      - uses: actions/checkout@v4

      - name: Add PHP, Composer and npm to PATH
        run: echo "/opt/homebrew/opt/php@8.1/bin:/usr/local/bin:/opt/homebrew/bin" >> $GITHUB_PATH

      - name: Check PHP version
        run: php -v

      - name: Check Composer version
        run: composer --version

      - name: Check npm version
        run: npm -v

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Install npm dependencies
        run: npm ci

      - name: Build frontend assets
        run: npm run build

      - name: Run Laravel migrations (production)
        run: php artisan migrate --force
        env:
          APP_ENV: production
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}

      - name: Done
        run: echo "✅ Nasadenie pre tag 2.106.2 je hotové!"
