on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: [self-hosted, macOS, X64]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - run: composer install --prefer-dist

      - name: Get npm cache directory
        id: npm-cache
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-

      - run: npm ci

      - name: Build assets
        run: npm run build

      - name: Test
        run: php artisan test
        env:
          APP_KEY: SomeRandomStringSomeRandomString
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: root
          DB_DATABASE: webumenia_test
          DB_PASSWORD: ""
          ELASTICSEARCH_HOST: 127.0.0.1
          ELASTICSEARCH_PORT: 9200
