name: Create a release

on:
  push:
    tags:
      #   - '*.*.*'
      - 'test-*'

jobs:
  release:
    # if: ${{ github.ref == 'refs/heads/master'  }}
    if: ${{ github.ref == 'refs/heads/WEBUMENIA-2012-automate-release-creations'  }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: true
