name: Test on push

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set .env file
        run: cp .env.example .env
      - name: Warm up stack
        run: docker-compose up -d mysql elasticsearch redis
      - name: Pull current image for cache
        run: docker pull slovaknationalgallery/webumenia:develop
      - name: Test
        run: docker-compose run php bash -c "npm run testing && vendor/bin/phpunit"
